// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DAL.Models
{
    public partial class biletler
    {
        public biletler()
        {
            bilet_firma_iliskisi = new HashSet<bilet_firma_iliskisi>();
            bilet_yolcu_iliskisi = new HashSet<bilet_yolcu_iliskisi>();
        }

        public Guid id { get; set; }
        public long biletUcreti { get; set; }
        public string biletAdi { get; set; }

        public virtual ICollection<bilet_firma_iliskisi> bilet_firma_iliskisi { get; set; }
        public virtual ICollection<bilet_yolcu_iliskisi> bilet_yolcu_iliskisi { get; set; }
    }
}