// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DAL.Models
{
    public partial class firma
    {
        public firma()
        {
            bilet_firma_iliskisi = new HashSet<bilet_firma_iliskisi>();
        }

        public Guid id { get; set; }
        public string firmaAdi { get; set; }

        public virtual ICollection<bilet_firma_iliskisi> bilet_firma_iliskisi { get; set; }
    }
}